USE PHOTO;
CREATE TABLE IF NOT EXISTS USER (
    ID INT(11) NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(250) NOT NULL UNIQUE,
    PASSWORD VARCHAR(100),
    PHONE VARCHAR(250),
    PRIMARY KEY (ID),
    INDEX (EMAIL)    
);

CREATE TABLE IF NOT EXISTS BOOKING (
    ID INT(11) NOT NULL AUTO_INCREMENT,
    CNAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(250) NOT NULL,
    PID VARCHAR(100),
    DATE VARCHAR(50),
    STATUS VARCHAR(50),
    PRIMARY KEY (ID),
    INDEX (EMAIL)
);

CREATE TABLE IF NOT EXISTS PHOTOGRAPHER(
    ID INT(11) NOT NULL AUTO_INCREMENT,
    PNAME VARCHAR(100) NOT NULL,
    PEMAIL VARCHAR(250),
    PID VARCHAR(100),
    PRIMARY KEY (ID),
    INDEX(PID)
);

INSERT INTO USER (NAME,EMAIL,PASSWORD,PHONE) VALUES ('admin','admin@gmail.com','admin123','1234567890');

INSERT INTO PHOTOGRAPHER (PNAME,PEMAIL,PID) VALUES ('Ramesh','ramesh@gmail.com','p1');
INSERT INTO PHOTOGRAPHER (PNAME,PEMAIL,PID) VALUES ('Suresh','suresh@gmail.com','p2');
INSERT INTO PHOTOGRAPHER (PNAME,PEMAIL,PID) VALUES ('Mahesh','mahesh@gmail.com','p1');